---
title: "Getting started with DAEDALUS"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started with DAEDALUS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette shows how to get started with the DAEDALUS model in R.

```{r libraries}
# load the package
library(daedalus)
library(ggplot2)
```

The model runs for 300 timesteps (assumed to be days) by default.
The `daedalus()` function documentation has more information on the pathogen parameter defaults in the **Details** section.

```{r run_model}
output <- daedalus("Canada")
```

Get the data in long or 'tidy' format using `prepare_output()`.

```{r get_data}
data <- prepare_output(output)

head(data)
```

Plot the data to view the epidemic curve.

```{r plot_epidemic}
ggplot(
  data[data$compartment == "infect_symp" & data$age_group == "20-65", ]
) +
  geom_line(
    aes(time, value, colour = econ_sector),
    show.legend = FALSE,
    position = "jitter"
  ) +
  facet_wrap(
    facets = vars(age_group)
  )
```
