---
title: "Daedalus features in development"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Daedalus features in development}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(daedalus)
```

This vignette is intended as a visual check on _daedalus_ features in development.

```{r}
output <- daedalus2("GBR", "influenza_2009")

plot(colSums(output$S))
plot(colSums(output$E))
plot(colSums(output$Is))
plot(colSums(output$Ia))
plot(colSums(output$H))
plot(colSums(output$R))
plot(colSums(output$D))
```

This should be a curve and not monotonically increasing.

```{r}
plot(colSums(output$new_inf))
plot(colSums(output$new_hosp))
```

## Vaccination

This section aims to be a visual check on vaccination in `daedalus2()` as the return type is not fully compatible with `daedalus()` output.

```{r}
# high vaccination rate but low uptake limit
vax <- daedalus_vaccination("high", uptake_limit = 40)
output <- daedalus2("GBR", "influenza_2009", vaccine_investment = vax)

# unvaccinated
plot(colSums(output$S))
plot(colSums(output$E))
plot(colSums(output$new_inf))
plot(colSums(output$new_hosp))

# vaccinated
plot(colSums(output$S_vax))
plot(colSums(output$E_vax))
plot(colSums(output$new_inf_vax))
plot(colSums(output$new_hosp_vax))
```

## Events

This section is a visual check on events.

```{r}
# trigger event on low hospital capacity
x <- daedalus_country("GBR")
x$hospital_capacity <- 1e4
x

output <- daedalus2(
  x, "influenza_2009",
  response_strategy = "elimination",
  time_end = 100
)

# expect a sharp drop in new infections
plot(colSums(output$E), type = "l")
plot(colSums(output$new_inf), type = "l")

plot(colSums(output$resp_flag), type = "l")
plot(colSums(output$growth_flag), type = "l")
```
