// Generated by cpp11: do not edit by hand
// clang-format off

#include "daedalus_types.h"
#include <cpp11/R.hpp>
#include <Rcpp.h>
using namespace Rcpp;
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// daedalus.cpp
SEXP dust2_system_daedalus_ode_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _daedalus_dust2_system_daedalus_ode_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_daedalus_ode_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// daedalus.cpp
SEXP dust2_system_daedalus_ode_internals(cpp11::sexp ptr, bool include_coefficients, bool include_history);
extern "C" SEXP _daedalus_dust2_system_daedalus_ode_internals(SEXP ptr, SEXP include_coefficients, SEXP include_history) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_daedalus_ode_internals(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(include_coefficients), cpp11::as_cpp<cpp11::decay_t<bool>>(include_history)));
  END_CPP11
}
// daedalus.cpp
SEXP dust2_system_daedalus_ode_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _daedalus_dust2_system_daedalus_ode_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_daedalus_ode_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// daedalus.cpp
SEXP dust2_system_daedalus_ode_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _daedalus_dust2_system_daedalus_ode_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_daedalus_ode_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// daedalus.cpp
SEXP dust2_system_daedalus_ode_time(cpp11::sexp ptr);
extern "C" SEXP _daedalus_dust2_system_daedalus_ode_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_daedalus_ode_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// daedalus.cpp
SEXP dust2_system_daedalus_ode_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _daedalus_dust2_system_daedalus_ode_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_daedalus_ode_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// daedalus.cpp
SEXP dust2_system_daedalus_ode_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _daedalus_dust2_system_daedalus_ode_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_daedalus_ode_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// daedalus.cpp
SEXP dust2_system_daedalus_ode_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _daedalus_dust2_system_daedalus_ode_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_daedalus_ode_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// daedalus.cpp
SEXP dust2_system_daedalus_ode_rng_state(cpp11::sexp ptr);
extern "C" SEXP _daedalus_dust2_system_daedalus_ode_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_daedalus_ode_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// daedalus.cpp
SEXP dust2_system_daedalus_ode_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _daedalus_dust2_system_daedalus_ode_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_daedalus_ode_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// daedalus.cpp
SEXP dust2_system_daedalus_ode_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _daedalus_dust2_system_daedalus_ode_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_daedalus_ode_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// daedalus.cpp
SEXP dust2_system_daedalus_ode_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _daedalus_dust2_system_daedalus_ode_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_daedalus_ode_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// daedalus.cpp
SEXP dust2_system_daedalus_ode_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _daedalus_dust2_system_daedalus_ode_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_daedalus_ode_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// scratch.cpp
cpp11::doubles get_omega_cpp11(cpp11::doubles hfr, const double gamma_H_recovery, const double gamma_H_death);
extern "C" SEXP _daedalus_get_omega_cpp11(SEXP hfr, SEXP gamma_H_recovery, SEXP gamma_H_death) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_omega_cpp11(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(hfr), cpp11::as_cpp<cpp11::decay_t<const double>>(gamma_H_recovery), cpp11::as_cpp<cpp11::decay_t<const double>>(gamma_H_death)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_daedalus_dust2_system_daedalus_ode_alloc",             (DL_FUNC) &_daedalus_dust2_system_daedalus_ode_alloc,             8},
    {"_daedalus_dust2_system_daedalus_ode_internals",         (DL_FUNC) &_daedalus_dust2_system_daedalus_ode_internals,         3},
    {"_daedalus_dust2_system_daedalus_ode_reorder",           (DL_FUNC) &_daedalus_dust2_system_daedalus_ode_reorder,           2},
    {"_daedalus_dust2_system_daedalus_ode_rng_state",         (DL_FUNC) &_daedalus_dust2_system_daedalus_ode_rng_state,         1},
    {"_daedalus_dust2_system_daedalus_ode_run_to_time",       (DL_FUNC) &_daedalus_dust2_system_daedalus_ode_run_to_time,       2},
    {"_daedalus_dust2_system_daedalus_ode_set_rng_state",     (DL_FUNC) &_daedalus_dust2_system_daedalus_ode_set_rng_state,     2},
    {"_daedalus_dust2_system_daedalus_ode_set_state",         (DL_FUNC) &_daedalus_dust2_system_daedalus_ode_set_state,         2},
    {"_daedalus_dust2_system_daedalus_ode_set_state_initial", (DL_FUNC) &_daedalus_dust2_system_daedalus_ode_set_state_initial, 1},
    {"_daedalus_dust2_system_daedalus_ode_set_time",          (DL_FUNC) &_daedalus_dust2_system_daedalus_ode_set_time,          2},
    {"_daedalus_dust2_system_daedalus_ode_simulate",          (DL_FUNC) &_daedalus_dust2_system_daedalus_ode_simulate,          5},
    {"_daedalus_dust2_system_daedalus_ode_state",             (DL_FUNC) &_daedalus_dust2_system_daedalus_ode_state,             6},
    {"_daedalus_dust2_system_daedalus_ode_time",              (DL_FUNC) &_daedalus_dust2_system_daedalus_ode_time,              1},
    {"_daedalus_dust2_system_daedalus_ode_update_pars",       (DL_FUNC) &_daedalus_dust2_system_daedalus_ode_update_pars,       2},
    {"_daedalus_get_omega_cpp11",                             (DL_FUNC) &_daedalus_get_omega_cpp11,                             3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_daedalus(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
