// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// model_daedalus_internal
Rcpp::List model_daedalus_internal(const Eigen::MatrixXd& initial_state, const Rcpp::List& params, const Eigen::MatrixXd& contact_matrix, const Eigen::ArrayXd& contacts_work, const Eigen::MatrixXd& contacts_consumers, const Eigen::ArrayXd& openness, const double& hospital_capacity, const double& t_start, const double& t_end, const bool auto_social_distancing, const double& social_distancing_mandate, const double& time_end, const double& increment);
RcppExport SEXP _daedalus_model_daedalus_internal(SEXP initial_stateSEXP, SEXP paramsSEXP, SEXP contact_matrixSEXP, SEXP contacts_workSEXP, SEXP contacts_consumersSEXP, SEXP opennessSEXP, SEXP hospital_capacitySEXP, SEXP t_startSEXP, SEXP t_endSEXP, SEXP auto_social_distancingSEXP, SEXP social_distancing_mandateSEXP, SEXP time_endSEXP, SEXP incrementSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type initial_state(initial_stateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type contact_matrix(contact_matrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type contacts_work(contacts_workSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type contacts_consumers(contacts_consumersSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type openness(opennessSEXP);
    Rcpp::traits::input_parameter< const double& >::type hospital_capacity(hospital_capacitySEXP);
    Rcpp::traits::input_parameter< const double& >::type t_start(t_startSEXP);
    Rcpp::traits::input_parameter< const double& >::type t_end(t_endSEXP);
    Rcpp::traits::input_parameter< const bool >::type auto_social_distancing(auto_social_distancingSEXP);
    Rcpp::traits::input_parameter< const double& >::type social_distancing_mandate(social_distancing_mandateSEXP);
    Rcpp::traits::input_parameter< const double& >::type time_end(time_endSEXP);
    Rcpp::traits::input_parameter< const double& >::type increment(incrementSEXP);
    rcpp_result_gen = Rcpp::wrap(model_daedalus_internal(initial_state, params, contact_matrix, contacts_work, contacts_consumers, openness, hospital_capacity, t_start, t_end, auto_social_distancing, social_distancing_mandate, time_end, increment));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_daedalus_model_daedalus_internal", (DL_FUNC) &_daedalus_model_daedalus_internal, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_daedalus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
