## Generated by dust2 (version 0.3.25) - do not edit
daedalus_ode <- structure(
  function() get("daedalus_ode"),
  class = "dust_system_generator",
  name = "daedalus_ode",
  package = "daedalus",
  path = NULL,
  parameters = data.frame(
    name = c("beta", "sigma", "p_sigma", "epsilon", "rho", "eta", "hfr", "gamma_Ia", "gamma_Is", "gamma_H_recovery", "gamma_H_death", "nu", "susc", "psi", "n_age_groups", "n_econ_groups", "popsize", "cm", "cm_work", "cm_cons_work", "hospital_capacity", "openness", "auto_social_distancing"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "int", "int", "int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)),
  properties = list(
    time_type = "mixed",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = NULL)
