## Generated by dust2 (version 0.3.16) - do not edit
daedalus_ode <- structure(
  function() get("daedalus_ode"),
  class = "dust_system_generator",
  name = "daedalus_ode",
  package = "daedalus",
  path = NULL,
  parameters = data.frame(
    name = c("I0", "N", "beta", "sigma", "gamma", "n_strata", "conmat"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "int", "real_type"),
    constant = c(FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE)),
  properties = list(
    time_type = "continuous",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = NULL)
