# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.model_daedalus_cpp <- function(initial_state, params, contact_matrix, time_end = 100.0, increment = 1.0) {
    .Call(`_daedalus_model_daedalus_internal`, initial_state, params, contact_matrix, time_end, increment)
}

